import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from './../components/layouts/Navbar';
import Footer from "@/components/layouts/Footer";
import localFont from 'next/font/local'
import NextAuthProvider from "@/provider/NextAuthProvider";
export const poppins = Poppins({
  weight: ["100","200","400","500","600","700"]
})
export const banglaFont = localFont({
  src: './fonts/mayaboti-normal.ttf',
})
export const metadata = {
  title: {
    default: "Hero Kidz",
    template: "%s | Hero Kidz"
  },
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body
        className={`${poppins.className} antialiased  `}
      >
        <header>
          <Navbar></Navbar>
        </header>
        <main className="min-h-[calc(100svh-320px)] w-11/12 mx-auto">
          {children}
        </main>
        <footer>
          <Footer></Footer>
        </footer>

      </body>
      </NextAuthProvider>
    </html>
  );
}
