import Products from '@/components/Products/Products';
import React from 'react';
export const metadata = {
  title: "All Products",
  description: "Generated by create next app",
};
const page = () => {
    return (
        <div>
            <Products></Products>
        </div>
    );
};

export default page;